services:
  sciml-sandbox:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    shm_size: '1gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    container_name: "sciml-sandbox"
    volumes:
      - ../:/sciml-sandbox
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]